# Generated by Django 5.0.6 on 2026-05-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semaforo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único de identificação",
                        max_length=20,
                        unique=True,
                        verbose_name="código do semáforo",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VERDE", "Verde"),
                            ("AMARELO", "Amarelo"),
                            ("VERMELHO", "Vermelho"),
                            ("APAGADO", "Apagado"),
                            ("MANUTENCAO", "Em Manutenção"),
                        ],
                        default="VERDE",
                        max_length=15,
                        verbose_name="status atual",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "via",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="semaforos",
                        to="vias.via",
                        verbose_name="via",
                    ),
                ),
            ],
            options={
                "verbose_name": "semáforo",
                "verbose_name_plural": "semáforos",
                "ordering": ["codigo"],
            },
        ),
    ]
