# Generated by Django 5.0.6 on 2026-05-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Via",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome da via")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AVENIDA", "Avenida"),
                            ("RUA", "Rua"),
                            ("RODOVIA", "Rodovia"),
                        ],
                        default="RUA",
                        max_length=20,
                        verbose_name="tipo de via",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="bairro"),
                ),
                (
                    "latitude_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "latitude_final",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude_final",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "via",
                "verbose_name_plural": "vias",
                "ordering": ["nome"],
            },
        ),
    ]
