# Generated by Django 5.2.13 on 2026-04-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='via',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='via',
            name='longitude',
        ),
        migrations.AddField(
            model_name='via',
            name='latitude_final',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='via',
            name='latitude_inicial',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='via',
            name='longitude_final',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='via',
            name='longitude_inicial',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
