# Generated by Django 6.0.4 on 2026-04-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),

        # campo criado_em
        migrations.AddField(
            model_name="usuario",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,  # manter se já existe dado antigo
            ),
        ),

        # foto
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                upload_to="usuarios/",
                verbose_name="Foto de perfil",
                blank=True,
                null=True,
            ),
        ),

        # telefone
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                max_length=20,
                verbose_name="Telefone",
                blank=True,
            ),
        ),

        # tipo
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                max_length=10,
                choices=[
                    ("CIDADAO", "Cidadão"),
                    ("AGENTE", "Agente de Trânsito"),
                    ("ADMIN", "Administrador"),
                ],
                default="CIDADAO",
                verbose_name="Tipo de usuário",
            ),
        ),
    ]