<<<<<<< HEAD
# Generated by Django 5.0.6 on 2026-04-24 00:46

import django.core.validators
import django.utils.timezone
=======
# Generated by Django 5.0.6 on 2026-04-23 23:33

import django.core.validators
>>>>>>> 154649d931cc7ae295a1ec8fed665a9da86bc548
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('usuarios', '0002_alter_usuario_options_usuario_criado_em_and_more'),
=======
        ("usuarios", "0002_alter_usuario_options_usuario_criado_em_and_more"),
>>>>>>> 154649d931cc7ae295a1ec8fed665a9da86bc548
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name='usuario',
            options={'ordering': ['-criado_em'], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'telefone inválido')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('CIDADAO', 'Cidadão'), ('AGENTE', 'Agente de Trânsito'), ('ADMIN', 'Administrador')], default='CIDADAO', max_length=10, verbose_name='tipo de usuário'),
=======
            name="usuario",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
        ),
        migrations.AlterField(
            model_name="usuario",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="usuarios/",
                verbose_name="foto de perfil",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10,11}$", "telefone inválido"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CIDADAO", "Cidadão"),
                    ("AGENTE", "Agente de Trânsito"),
                    ("ADMIN", "Administrador"),
                ],
                default="CIDADAO",
                max_length=10,
                verbose_name="tipo de usuário",
            ),
>>>>>>> 154649d931cc7ae295a1ec8fed665a9da86bc548
        ),
    ]
