# Generated by Django 5.0.6 on 2026-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_options_alter_usuario_criado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="codigo_expira_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="codigo_verificacao",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
