# Generated by Django 5.0.6 on 2026-05-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("semaforos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACIDENTE", "Acidente"),
                            ("SEMAFORO_DEFEITO", "Semáforo com Defeito"),
                            ("CONGESTIONAMENTO", "Congestionamento"),
                            ("OBRA", "Obra / Interdição"),
                            ("EVENTO", "Evento"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de ocorrência",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("RESOLVIDA", "Resolvida"),
                            ("ENCERRADA", "Encerrada"),
                        ],
                        default="ABERTA",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "semaforo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias",
                        to="semaforos.semaforo",
                        verbose_name="Semáforo relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
                "ordering": ["-criado_em"],
            },
        ),
    ]
