# Generated by Django 5.0.6 on 2026-04-26 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("semaforos", "0001_initial"),
        ("vias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACIDENTE", "Acidente"),
                            ("SEMAFORO_DEFEITO", "Semáforo com Defeito"),
                            ("CONGESTIONAMENTO", "Congestionamento de via"),
                            ("OBRA", "Obra na Via"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="tipo de ocorrência",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="descrição")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("RESOLVIDA", "Resolvida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=15,
                        verbose_name="situação",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "reportado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_reportadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reportado por",
                    ),
                ),
                (
                    "semaforo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias",
                        to="semaforos.semaforo",
                        verbose_name="semáforo relacionado",
                    ),
                ),
                (
                    "via",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocorrencias",
                        to="vias.via",
                        verbose_name="via",
                    ),
                ),
            ],
            options={
                "verbose_name": "ocorrência",
                "verbose_name_plural": "ocorrências",
                "ordering": ["-criado_em"],
            },
        ),
    ]
