# Generated by Django 5.0.6 on 2026-04-27 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0001_initial"),
        ("semaforos", "0001_initial"),
        ("vias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ocorrencia",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
            },
        ),
        migrations.RemoveField(
            model_name="ocorrencia",
            name="reportado_por",
        ),
        migrations.RemoveField(
            model_name="ocorrencia",
            name="situacao",
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTA", "Aberta"),
                    ("EM_ANDAMENTO", "Em Andamento"),
                    ("RESOLVIDA", "Resolvida"),
                    ("ENCERRADA", "Encerrada"),
                ],
                default="ABERTA",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocorrencias_reportadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrada por",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="semaforo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocorrencias",
                to="semaforos.semaforo",
                verbose_name="Semáforo relacionado",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ACIDENTE", "Acidente"),
                    ("SEMAFORO_DEFEITO", "Semáforo com Defeito"),
                    ("CONGESTIONAMENTO", "Congestionamento"),
                    ("OBRA", "Obra / Interdição"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo de ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="via",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocorrencias",
                to="vias.via",
                verbose_name="Via/Rua",
            ),
        ),
    ]
