# Generated by Django 5.0.6 on 2026-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
    ]
