# Generated by Django 5.0.6 on 2026-05-05 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocorrencias', '0001_initial'),
        ('vias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='via',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='vias.via', verbose_name='Via/Rua'),
        ),
    ]
