# Generated by Django 5.0.6 on 2026-05-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0002_alter_ocorrencia_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ACIDENTE", "Acidente"),
                    ("SEMAFORO_DEFEITO", "Semáforo com Defeito"),
                    ("CONGESTIONAMENTO", "Congestionamento"),
                    ("OBRA", "Obra / Interdição"),
                    ("EVENTO", "Evento"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo de ocorrência",
            ),
        ),
    ]
