# Generated by Django 5.0.6 on 2026-04-30 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0003_ocorrencia_usuario"),
        ("vias", "0002_remove_via_latitude_remove_via_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocorrencia",
            name="foto",
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTA", "Aberta"),
                    ("EM_ANDAMENTO", "Em Andamento"),
                    ("RESOLVIDA", "Resolvida"),
                    ("ENCERRADA", "Encerrada"),
                ],
                default="ABERTA",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ACIDENTE", "Acidente"),
                    ("SEMAFORO_DEFEITO", "Semáforo com Defeito"),
                    ("CONGESTIONAMENTO", "Congestionamento"),
                    ("OBRA", "Obra / Interdição"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo de ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="via",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocorrencias",
                to="vias.via",
                verbose_name="Via/Rua",
            ),
        ),
    ]
