# Generated by Django 5.0.6 on 2026-05-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0003_alter_ocorrencia_tipo"),
        ("ocorrencias", "0004_remove_ocorrencia_foto_alter_ocorrencia_status_and_more"),
    ]

    operations = []
