# Generated by Django 5.0.6 on 2026-05-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0005_merge_20260501_1955"),
        ("ocorrencias", "0005_merge_20260501_2322"),
    ]

    operations = []
